AWSTemplateFormatVersion: 2010-09-09
Description: Mervin Academy Demo CloudFormation

Resources:

  MerviVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: MerviVPC
        - Key: Owner
          Value: Mervi

  MerviSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MerviVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "eu-west-1a"
      Tags:
        - Key: Name
          Value: MerviSubnetA
        - Key: Owner
          Value: Mervi
      MapPublicIpOnLaunch: True

  MerviSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MerviVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "eu-west-1b"
      Tags:
        - Key: Name
          Value: MerviSubnetB
        - Key: Owner
          Value: Mervi

  MerviSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MerviVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "eu-west-1c"
      Tags:
        - Key: Name
          Value: MerviSubnetC
        - Key: Owner
          Value: Mervi

  MerviInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MerviInternetGateway
        - Key: Owner
          Value: Mervi


  MerviAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: MerviVPC
      InternetGatewayId:
        Ref: MerviInternetGateway

  NAT:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - MerviEIP
          - AllocationId
      SubnetId:
        Ref: MerviSubnetA
      Tags:
        - Key: Name
          Value: MerviNAT
        - Key: Owner
          Value: Mervi

  MerviEIP:
    DependsOn: MerviAttachGateway
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  MerviRouteA:
    Type: AWS::EC2::Route
    DependsOn: MerviAttachGateway
    Properties:
      RouteTableId:
        Ref: MerviRouteTableA
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: MerviInternetGateway

  MerviRouteB:
    Type: AWS::EC2::Route
    DependsOn: MerviAttachGateway
    Properties:
      RouteTableId:
        Ref: MerviRouteTableB
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: NAT

  MerviRouteC:
    Type: AWS::EC2::Route
    DependsOn: MerviAttachGateway
    Properties:
      RouteTableId:
        Ref: MerviRouteTableC
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: NAT

  MerviRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MerviVPC
      Tags:
        - Key: Name
          Value: MerviRouteTableA

  MerviRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MerviVPC
      Tags:
        - Key: Name
          Value: MerviRouteTableB

  MerviRouteTableC:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MerviVPC
      Tags:
        - Key: Name
          Value: MerviRouteTableC

  MerviSubnetRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: MerviSubnetA
      RouteTableId:
        Ref: MerviRouteTableA

  MerviSubnetRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: MerviSubnetB
      RouteTableId:
        Ref: MerviRouteTableB

  MerviSubnetRouteTableAssociationC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: MerviSubnetC
      RouteTableId:
        Ref: MerviRouteTableC

Outputs:
  VpcId:
    Value: !Ref MerviVPC
  SubnetAId:
    Value: !Ref MerviSubnetA
  SubnetBId:
    Value: !Ref MerviSubnetB
  SubnetCId:
    Value: !Ref MerviSubnetC