AWSTemplateFormatVersion: 2010-09-09
Description: Mervin Academy Demo CloudFormation

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  ApplicationPort:
    Type: Number
    Default: 80

Resources:
  Buketti:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mervin-academy-cf-demo-bucket
      Tags:
        - Key: Owner
          Value: Mervi

  Sqsmervi:
    Type: AWS::SQS::Queue
    Properties:
       QueueName: String
       Tags:
        - Key: Owner
          Value: Mervi

  EC2mervi:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: Mervi-cf-ec2

  ALBMervi:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - subnet-2f0cdc70
        - subnet-46b73e48
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2
      GroupName: mervi-cf-ec2-security-group
      SecurityGroupIngress:
        FromPort: !Ref ApplicationPort
        IpProtocol: tcp
        SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
        ToPort: !Ref ApplicationPort
      VpcId: vpc-bc8f6cc1

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2
      GroupName: mervi-cf-alb-security-group
      VpcId: vpc-bc8f6cc1
      SecurityGroupIngress:
        FromPort: !Ref ApplicationPort
        IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        ToPort: !Ref ApplicationPort

  LoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: Mervi-LB-TG-1
      Port: !Ref ApplicationPort
      Protocol: HTTP
      TargetType: instance
      Tags:
        - Key: Name
          Value: LoadBalancer-TG
      VpcId: vpc-bc8f6cc1

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref LoadBalancerTargetGroup
      LoadBalancerArn: !Ref ALBMervi
      Port: !Ref ApplicationPort
      Protocol: HTTP


Outputs:
  BackupLoadBalancerDNSName:
    Description: The DNSName of the backup load balancer
    Value: !GetAtt ALBMervi.DNSName



