AWSTemplateFormatVersion: 2010-09-09
Description: Mervin Academy Demo CloudFormation

Resources:
  Buketti:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mervin-academy-cf-demo-bucket
      Tags:
        - Key: Owner
          Value: Mervi

  Sqsmervi:
    Type: AWS::SQS::Queue
    Properties:
       QueueName: String
       Tags:
        - Key: Owner
          Value: Mervi

