AWSTemplateFormatVersion: 2010-09-09
Description: Mervin Academy Demo CloudFormation

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  Buketti:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mervin-academy-cf-demo-bucket
      Tags:
        - Key: Owner
          Value: Mervi

  Sqsmervi:
    Type: AWS::SQS::Queue
    Properties:
       QueueName: String
       Tags:
        - Key: Owner
          Value: Mervi

  EC2mervi:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId

  ALBMervi:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - subnet-2f0cdc70
        - subnet-46b73e48



