AWSTemplateFormatVersion: 2010-09-09
Description: Mervin Academy Demo CloudFormation

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  ApplicationPort:
    Type: Number
    Default: 80
#  VpcId:
#    Type: String
#    Default: !GetAtt MerviNested.Outputs.VpcId
#  SubnetAId:
#    Type: String
#    Default: !GetAtt MerviNested.Outputs.SubnetAId
#  SubnetBId:
#    Type: String
#    Default: !GetAtt MerviNested.Outputs.SubnetBId
#  SubnetCId:
#    Type: String
#    Default: !GetAtt MerviNested.Outputs.SubnetCId

Resources:
  MerviNested:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://mervi-cf-buketti.s3-eu-west-1.amazonaws.com/arkkitehtuuriteht._8.yaml

  LaunchConfigMervi:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-0c3e74fa87d2a4227
      UserData:
        Fn::Base64:
          Fn::Join:
            - "\n"
            - - "#!/bin/bash"
              - "amazon-linux-extras install epel"
              - "amazon-linux-extras install nginx1"
              - "systemctl start nginx"
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      InstanceType: t2.micro

  AutoScalingMervi:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: Mervi-AutoScalingGroup
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 2
      HealthCheckGracePeriod: 150
      LaunchConfigurationName: !Ref LaunchConfigMervi
      VPCZoneIdentifier:
        - !GetAtt MerviNested.Outputs.SubnetAId
        - !GetAtt MerviNested.Outputs.SubnetBId
        - !GetAtt MerviNested.Outputs.SubnetCId
      TargetGroupARNs:
        - !Ref LoadBalancerTargetGroup

  Buketti:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mervin-academy-cf-demo-bucket
      Tags:
        - Key: Owner
          Value: Mervi

  Sqsmervi:
    Type: AWS::SQS::Queue
    Properties:
       QueueName: String
       Tags:
        - Key: Owner
          Value: Mervi

  ALBMervi:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - !GetAtt MerviNested.Outputs.SubnetAId
        - !GetAtt MerviNested.Outputs.SubnetBId
        - !GetAtt MerviNested.Outputs.SubnetCId
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2
      GroupName: mervi-cf-ec2-security-group
      SecurityGroupIngress:
        FromPort: !Ref ApplicationPort
        IpProtocol: tcp
        SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
        ToPort: !Ref ApplicationPort
      VpcId: !GetAtt MerviNested.Outputs.VpcId

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2
      GroupName: mervi-cf-alb-security-group
      VpcId: !GetAtt MerviNested.Outputs.VpcId
      SecurityGroupIngress:
        FromPort: !Ref ApplicationPort
        IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        ToPort: !Ref ApplicationPort

  LoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: Mervi-LB-TG-1
      Port: !Ref ApplicationPort
      Protocol: HTTP
      TargetType: instance
      Tags:
        - Key: Name
          Value: LoadBalancer-TG
      VpcId: !GetAtt MerviNested.Outputs.VpcId

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref LoadBalancerTargetGroup
      LoadBalancerArn: !Ref ALBMervi
      Port: !Ref ApplicationPort
      Protocol: HTTP


Outputs:
  BackupLoadBalancerDNSName:
    Description: The DNSName of the backup load balancer
    Value: !GetAtt ALBMervi.DNSName



